// Lista local de exames comuns (laboratoriais e de imagem)
export const EXAMS: string[] = [
  // Hematologia
  "Hemograma completo",
  "Plaquetas",
  "Coagulograma (TAP/INR/TTPA)",
  "VHS",
  "Reticulócitos",
  // Bioquímica
  "Glicemia de jejum",
  "Hemoglobina glicada (HbA1c)",
  "Curva glicêmica",
  "Insulina basal",
  "Colesterol total e frações",
  "Triglicerídeos",
  "Ureia",
  "Creatinina",
  "Ácido úrico",
  "TGO (AST)",
  "TGP (ALT)",
  "Gama GT",
  "Fosfatase alcalina",
  "Bilirrubinas totais e frações",
  "Sódio",
  "Potássio",
  "Cálcio total",
  "Cálcio iônico",
  "Magnésio",
  "Fósforo",
  "Ferro sérico",
  "Ferritina",
  "Transferrina",
  "Vitamina D (25-OH)",
  "Vitamina B12",
  "Ácido fólico",
  // Hormônios
  "TSH",
  "T4 livre",
  "T3",
  "Anti-TPO",
  "Cortisol",
  "Testosterona total",
  "Testosterona livre",
  "Estradiol",
  "Progesterona",
  "FSH",
  "LH",
  "Prolactina",
  "PSA total",
  "PSA livre",
  "Beta-HCG",
  // Imunologia / Sorologias
  "PCR (Proteína C reativa)",
  "Fator reumatoide",
  "FAN",
  "Anti-HIV",
  "VDRL",
  "HBsAg",
  "Anti-HCV",
  "IgG e IgM CMV",
  "IgG e IgM toxoplasmose",
  "IgG e IgM rubéola",
  // Urina e fezes
  "EAS (urina tipo I)",
  "Urocultura",
  "Parasitológico de fezes",
  "Sangue oculto nas fezes",
  // Imagem
  "Raio-X de tórax PA e perfil",
  "Raio-X de coluna lombar",
  "Raio-X de coluna cervical",
  "Raio-X panorâmico (odontológico)",
  "Ultrassonografia de abdome total",
  "Ultrassonografia pélvica",
  "Ultrassonografia transvaginal",
  "Ultrassonografia de tireoide",
  "Ultrassonografia das mamas",
  "Mamografia bilateral",
  "Tomografia computadorizada de crânio",
  "Tomografia computadorizada de tórax",
  "Tomografia computadorizada de abdome",
  "Ressonância magnética de crânio",
  "Ressonância magnética de coluna lombar",
  "Ressonância magnética de joelho",
  "Densitometria óssea",
  // Cardiologia
  "Eletrocardiograma (ECG)",
  "Ecocardiograma transtorácico",
  "Teste ergométrico",
  "Holter 24h",
  "MAPA 24h",
  // Outros
  "Endoscopia digestiva alta",
  "Colonoscopia",
  "Espirometria",
  "Audiometria",
];

export function searchExams(query: string): string[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return EXAMS.filter((e) => e.toLowerCase().includes(q)).slice(0, 8);
}
